<?xml version="1.0" encoding="utf-8"?><Database Name="DDS" Class="DDSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MAURO-PC\SQLSERVER2008;Initial Catalog=DDS;Integrated Security=True" SettingsObjectName="TP_Anual_DDS_E4.Properties.Settings" SettingsPropertyName="DDSConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DBAmigos" Member="DBAmigos">
    <Type Name="DBAmigos">
      <Column Name="Id_Interesado" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Id_Amigo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="DBInteresado_DBAmigos" Member="DBInteresado" ThisKey="Id_Interesado" OtherKey="Id_Interesado" Type="DBInteresado" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBTipoJugador" Member="DBTipoJugador">
    <Type Name="DBTipoJugador">
      <Column Name="Id_TipoJugador" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="DBTipoJugador_DBPartido_Interesado" Member="DBPartido_Interesado" ThisKey="Id_TipoJugador" OtherKey="Id_TipoJugador" Type="DBPartido_Interesado" />
    </Type>
  </Table>
  <Table Name="dbo.DBCalificacion" Member="DBCalificacion">
    <Type Name="DBCalificacion">
      <Column Name="Id_Calificacion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_Partido" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Id_Jugador_Critico" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_Jugador_Criticado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Calificacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DBPartido_DBCalificacion" Member="DBPartido" ThisKey="Id_Partido" OtherKey="Id_Partido" Type="DBPartido" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBCondicion" Member="DBCondicion">
    <Type Name="DBCondicion">
      <Column Name="Id_Condicion" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Descripcion_Condicion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DBCondicion_DBCondicion_Interesado" Member="DBCondicion_Interesado" ThisKey="Id_Condicion" OtherKey="Id_Condicion" Type="DBCondicion_Interesado" />
      <Association Name="DBCondicion_DBPartido_Interesado_Condicional" Member="DBPartido_Interesado_Condicional" ThisKey="Id_Condicion" OtherKey="Id_Condicion" Type="DBPartido_Interesado_Condicional" />
    </Type>
  </Table>
  <Table Name="dbo.DBCondicion_Interesado" Member="DBCondicion_Interesado">
    <Type Name="DBCondicion_Interesado">
      <Column Name="Id_Condicion" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Id_interesado" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DBCondicion_DBCondicion_Interesado" Member="DBCondicion" ThisKey="Id_Condicion" OtherKey="Id_Condicion" Type="DBCondicion" IsForeignKey="true" />
      <Association Name="DBInteresado_DBCondicion_Interesado" Member="DBInteresado" ThisKey="Id_interesado" OtherKey="Id_Interesado" Type="DBInteresado" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBDenegacion" Member="DBDenegacion">
    <Type Name="DBDenegacion">
      <Column Name="Id_Denegacion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_Interesado" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Id_Usuario" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Fecha_Denegacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Descripcion_motivo_Denegacion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Id_Admin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DBInteresado_DBDenegacion" Member="DBInteresado" ThisKey="Id_Interesado" OtherKey="Id_Interesado" Type="DBInteresado" IsForeignKey="true" />
      <Association Name="DBUsuario_DBDenegacion" Member="DBUsuario" ThisKey="Id_Usuario" OtherKey="Id_Usuario" Type="DBUsuario" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBEstandar" Member="DBEstandar">
    <Type Name="DBEstandar">
      <Column Name="Modalidad_deJuego" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Descripcion_Estandar" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Prioridad" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBInfraccion" Member="DBInfraccion">
    <Type Name="DBInfraccion">
      <Column Name="Id_Infraccion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion_Infraccion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Id_Usuario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DBUsuario_DBInfraccion" Member="DBUsuario" ThisKey="Id_Usuario" OtherKey="Id_Usuario" Type="DBUsuario" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.DBInteresado" Member="DBInteresado">
    <Type Name="DBInteresado">
      <Column Name="Id_Interesado" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_Usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Posicion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Handicap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantPartidosJugados" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DBInteresado_DBAmigos" Member="DBAmigos" ThisKey="Id_Interesado" OtherKey="Id_Interesado" Type="DBAmigos" />
      <Association Name="DBInteresado_DBCondicion_Interesado" Member="DBCondicion_Interesado" ThisKey="Id_Interesado" OtherKey="Id_interesado" Type="DBCondicion_Interesado" />
      <Association Name="DBInteresado_DBDenegacion" Member="DBDenegacion" ThisKey="Id_Interesado" OtherKey="Id_Interesado" Type="DBDenegacion" />
      <Association Name="DBInteresado_DBPartido_Interesado" Member="DBPartido_Interesado" ThisKey="Id_Interesado" OtherKey="Id_Interesado" Type="DBPartido_Interesado" />
      <Association Name="DBInteresado_DBPartido_Interesado_Condicional" Member="DBPartido_Interesado_Condicional" ThisKey="Id_Interesado" OtherKey="Id_Interesado" Type="DBPartido_Interesado_Condicional" />
      <Association Name="DBUsuario_DBInteresado" Member="DBUsuario" ThisKey="Id_Usuario" OtherKey="Id_Usuario" Type="DBUsuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBPartido" Member="DBPartido">
    <Type Name="DBPartido">
      <Column Name="Id_Partido" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Lugar" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Confirmado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Fecha_Hora" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Finalizado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DBPartido_DBCalificacion" Member="DBCalificacion" ThisKey="Id_Partido" OtherKey="Id_Partido" Type="DBCalificacion" />
      <Association Name="DBPartido_DBPartido_Interesado" Member="DBPartido_Interesado" ThisKey="Id_Partido" OtherKey="Id_Partido" Type="DBPartido_Interesado" />
      <Association Name="DBPartido_DBPartido_Interesado_Condicional" Member="DBPartido_Interesado_Condicional" ThisKey="Id_Partido" OtherKey="Id_Partido" Type="DBPartido_Interesado_Condicional" />
    </Type>
  </Table>
  <Table Name="dbo.DBPartido_Interesado" Member="DBPartido_Interesado">
    <Type Name="DBPartido_Interesado">
      <Column Name="Id_Partido" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Id_Interesado" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Id_TipoJugador" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EquipoDesignado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Baja" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DBInteresado_DBPartido_Interesado" Member="DBInteresado" ThisKey="Id_Interesado" OtherKey="Id_Interesado" Type="DBInteresado" IsForeignKey="true" />
      <Association Name="DBPartido_DBPartido_Interesado" Member="DBPartido" ThisKey="Id_Partido" OtherKey="Id_Partido" Type="DBPartido" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="DBTipoJugador_DBPartido_Interesado" Member="DBTipoJugador" ThisKey="Id_TipoJugador" OtherKey="Id_TipoJugador" Type="DBTipoJugador" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBPartido_Interesado_Condicional" Member="DBPartido_Interesado_Condicional">
    <Type Name="DBPartido_Interesado_Condicional">
      <Column Name="Id_Partido" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Id_Interesado" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Id_Condicion" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Baja" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DBCondicion_DBPartido_Interesado_Condicional" Member="DBCondicion" ThisKey="Id_Condicion" OtherKey="Id_Condicion" Type="DBCondicion" IsForeignKey="true" />
      <Association Name="DBInteresado_DBPartido_Interesado_Condicional" Member="DBInteresado" ThisKey="Id_Interesado" OtherKey="Id_Interesado" Type="DBInteresado" IsForeignKey="true" />
      <Association Name="DBPartido_DBPartido_Interesado_Condicional" Member="DBPartido" ThisKey="Id_Partido" OtherKey="Id_Partido" Type="DBPartido" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBSolidario" Member="DBSolidario">
    <Type Name="DBSolidario">
      <Column Name="Modalidad_deJuego" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Descripcion_Estandar" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Datos_contacto" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Prioridad" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBUsuario" Member="DBUsuario">
    <Type Name="DBUsuario">
      <Column Name="Id_Usuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre_Usuario" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password_Usuario" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Usuario_Administrador" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DBUsuario_DBDenegacion" Member="DBDenegacion" ThisKey="Id_Usuario" OtherKey="Id_Usuario" Type="DBDenegacion" />
      <Association Name="DBUsuario_DBInfraccion" Member="DBInfraccion" ThisKey="Id_Usuario" OtherKey="Id_Usuario" Type="DBInfraccion" />
      <Association Name="DBUsuario_DBInteresado" Member="DBInteresado" ThisKey="Id_Usuario" OtherKey="Id_Usuario" Type="DBInteresado" />
    </Type>
  </Table>
  <Function Name="dbo.Buscar_Jugadores_L" Method="Buscar_Jugadores_L">
    <Parameter Name="nombre_jugador" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="fecha_nacimiento" Type="System.DateTime" DbType="Date" />
    <Parameter Name="handicap_desde" Type="System.Int32" DbType="Int" />
    <Parameter Name="handicap_hasta" Type="System.Int32" DbType="Int" />
    <Parameter Name="promedio_desde" Type="System.Decimal" DbType="Decimal(5,2)" />
    <Parameter Name="promedio_hasta" Type="System.Decimal" DbType="Decimal(5,2)" />
    <Parameter Name="infracciones" Type="System.Int32" DbType="Int" />
    <ElementType Name="Buscar_Jugadores_LResult">
      <Column Name="Id_Interesado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Handicap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantPartidosJugados" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.UsuarioInteresado_Obtener" Method="UsuarioInteresado_Obtener">
    <Parameter Name="Nombre_Usuario" Parameter="nombre_Usuario" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password_Usuario" Parameter="password_Usuario" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="UsuarioInteresado_ObtenerResult">
      <Column Name="Nombre_Usuario" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password_Usuario" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Id_Usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Posicion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Handicap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantPartidosJugados" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Calificacion_I" Method="Calificacion_I">
    <Parameter Name="Id_Partido" Parameter="id_Partido" Type="System.Int32" DbType="Int" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Id_Jugador_Critico" Parameter="id_Jugador_Critico" Type="System.Int32" DbType="Int" />
    <Parameter Name="Id_Jugador_Criticado" Parameter="id_Jugador_Criticado" Type="System.Int32" DbType="Int" />
    <Parameter Name="Calificacion" Parameter="calificacion" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Infraccion_I" Method="Infraccion_I">
    <Parameter Name="Id_Usuario" Parameter="id_Usuario" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Infraccion_L" Method="Infraccion_L">
    <ElementType Name="Infraccion_LResult">
      <Column Name="Nombre_Usuario" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password_Usuario" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Posicion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Handicap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantPartidosJugados" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Interesado_Detalle_L" Method="Interesado_Detalle_L">
    <Parameter Name="Id_Interesado" Parameter="id_Interesado" Type="System.Int32" DbType="Int" />
    <ElementType Name="Interesado_Detalle_LResult">
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Handicap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PromUltimo" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PromTodos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="cantJugados" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Interesado_Infracciones_L" Method="Interesado_Infracciones_L">
    <Parameter Name="Id_Interesado" Parameter="id_Interesado" Type="System.Int32" DbType="Int" />
    <ElementType Name="Interesado_Infracciones_LResult">
      <Column Name="Id_Infraccion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion_Infraccion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Id_Usuario" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Interesado_ObtenerPartidosFinalizados" Method="Interesado_ObtenerPartidosFinalizados">
    <Parameter Name="Id_Interesado" Parameter="id_Interesado" Type="System.Int32" DbType="Int" />
    <ElementType Name="Interesado_ObtenerPartidosFinalizadosResult">
      <Column Name="Id_Partido" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Lugar" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Confirmado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Fecha_Hora" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Finalizado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Interesado_UI" Method="Interesado_UI">
    <Parameter Name="Id_Usuario" Parameter="id_Usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Apellido" Parameter="apellido" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="FechaNacimiento" Parameter="fechaNacimiento" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Mail" Parameter="mail" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Posicion" Parameter="posicion" Type="System.Int32" DbType="Int" />
    <Parameter Name="Handicap" Parameter="handicap" Type="System.Int32" DbType="Int" />
  </Function>
  <Function Name="dbo.Partido_Interesado_Condicional_D" Method="Partido_Interesado_Condicional_D">
    <Parameter Name="Id_Partido" Parameter="id_Partido" Type="System.Int32" DbType="Int" />
    <Parameter Name="Id_Interesado" Parameter="id_Interesado" Type="System.Int32" DbType="Int" />
    <Parameter Name="Id_Condicion" Parameter="id_Condicion" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Partido_Interesado_Condicional_UI" Method="Partido_Interesado_Condicional_UI">
    <Parameter Name="Id_Partido" Parameter="id_Partido" Type="System.Int32" DbType="Int" />
    <Parameter Name="Id_Interesado" Parameter="id_Interesado" Type="System.Int32" DbType="Int" />
    <Parameter Name="Id_Condicion" Parameter="id_Condicion" Type="System.Int32" DbType="Int" />
    <Parameter Name="Baja" Parameter="baja" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Partido_Interesado_D" Method="Partido_Interesado_D">
    <Parameter Name="Id_Partido" Parameter="id_Partido" Type="System.Int32" DbType="Int" />
    <Parameter Name="Id_Interesado" Parameter="id_Interesado" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Partido_Interesado_L" Method="Partido_Interesado_L">
    <Parameter Name="Id_Partido" Parameter="id_Partido" Type="System.Int32" DbType="Int" />
    <ElementType Name="Partido_Interesado_LResult">
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Posicion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Handicap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Partido_Interesado_UI" Method="Partido_Interesado_UI">
    <Parameter Name="Id_Partido" Parameter="id_Partido" Type="System.Int32" DbType="Int" />
    <Parameter Name="Id_Interesado" Parameter="id_Interesado" Type="System.Int32" DbType="Int" />
    <Parameter Name="Tipo_Jugador" Parameter="tipo_Jugador" Type="System.Int32" DbType="Int" />
    <Parameter Name="Baja" Parameter="baja" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Partido_L" Method="Partido_L">
    <ElementType Name="Partido_LResult">
      <Column Name="Lugar" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_Hora" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Confirmado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Finalizado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Partido_ObtenerInteresados" Method="Partido_ObtenerInteresados">
    <Parameter Name="Id_Partido" Parameter="id_Partido" Type="System.Int32" DbType="Int" />
    <ElementType Name="Partido_ObtenerInteresadosResult">
      <Column Name="Nombre_Usuario" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password_Usuario" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Posicion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Handicap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantPartidosJugados" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Partido_UI" Method="Partido_UI">
    <Parameter Name="Lugar" Parameter="lugar" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Confirmado" Parameter="confirmado" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Fecha_Hora" Parameter="fecha_Hora" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Usuario_L" Method="Usuario_L">
    <ElementType Name="Usuario_LResult">
      <Column Name="Id_Usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre_Usuario" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password_Usuario" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Posicion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Handicap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantPartidosJugados" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Usuario_UI" Method="Usuario_UI">
    <Parameter Name="Nombre_Usuario" Parameter="nombre_Usuario" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password_Usuario" Parameter="password_Usuario" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Usuario_Administrador" Parameter="usuario_Administrador" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ObtenerJugadoresTraicioneros" Method="ObtenerJugadoresTraicioneros">
    <ElementType Name="ObtenerJugadoresTraicionerosResult">
      <Column Name="Id_Interesado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Posicion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Handicap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantPartidosJugados" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ObtenerJugadoresMalos" Method="ObtenerJugadoresMalos">
    <ElementType Name="ObtenerJugadoresMalosResult">
      <Column Name="Id_Interesado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Posicion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Handicap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantPartidosJugados" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ObtenerJugadoresConFuturo" Method="ObtenerJugadoresConFuturo">
    <ElementType Name="ObtenerJugadoresConFuturoResult">
      <Column Name="Id_Usuario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_Interesado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Posicion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Handicap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantPartidosJugados" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PromUltimoPartido" Method="PromUltimoPartido" IsComposable="true">
    <Parameter Name="Id_Interesado" Parameter="id_Interesado" Type="System.Int32" DbType="Int" />
    <Return Type="System.Decimal" />
  </Function>
</Database>