#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_Anual_DDS_E4
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DDS")]
	public partial class DDSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertDBAmigos(DBAmigos instance);
    partial void UpdateDBAmigos(DBAmigos instance);
    partial void DeleteDBAmigos(DBAmigos instance);
    partial void InsertDBUsuario(DBUsuario instance);
    partial void UpdateDBUsuario(DBUsuario instance);
    partial void DeleteDBUsuario(DBUsuario instance);
    partial void InsertDBCalificacion(DBCalificacion instance);
    partial void UpdateDBCalificacion(DBCalificacion instance);
    partial void DeleteDBCalificacion(DBCalificacion instance);
    partial void InsertDBCondicion(DBCondicion instance);
    partial void UpdateDBCondicion(DBCondicion instance);
    partial void DeleteDBCondicion(DBCondicion instance);
    partial void InsertDBCondicion_Interesado(DBCondicion_Interesado instance);
    partial void UpdateDBCondicion_Interesado(DBCondicion_Interesado instance);
    partial void DeleteDBCondicion_Interesado(DBCondicion_Interesado instance);
    partial void InsertDBDenegacion(DBDenegacion instance);
    partial void UpdateDBDenegacion(DBDenegacion instance);
    partial void DeleteDBDenegacion(DBDenegacion instance);
    partial void InsertDBInfraccion(DBInfraccion instance);
    partial void UpdateDBInfraccion(DBInfraccion instance);
    partial void DeleteDBInfraccion(DBInfraccion instance);
    partial void InsertDBInteresado(DBInteresado instance);
    partial void UpdateDBInteresado(DBInteresado instance);
    partial void DeleteDBInteresado(DBInteresado instance);
    partial void InsertDBPartido(DBPartido instance);
    partial void UpdateDBPartido(DBPartido instance);
    partial void DeleteDBPartido(DBPartido instance);
    partial void InsertDBPartido_Interesado(DBPartido_Interesado instance);
    partial void UpdateDBPartido_Interesado(DBPartido_Interesado instance);
    partial void DeleteDBPartido_Interesado(DBPartido_Interesado instance);
    #endregion
		
	
		
		public DDSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DDSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DDSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DDSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DBAmigos> DBAmigos
		{
			get
			{
				return this.GetTable<DBAmigos>();
			}
		}
		
		public System.Data.Linq.Table<DBUsuario> DBUsuario
		{
			get
			{
				return this.GetTable<DBUsuario>();
			}
		}
		
		public System.Data.Linq.Table<DBCalificacion> DBCalificacion
		{
			get
			{
				return this.GetTable<DBCalificacion>();
			}
		}
		
		public System.Data.Linq.Table<DBCondicion> DBCondicion
		{
			get
			{
				return this.GetTable<DBCondicion>();
			}
		}
		
		public System.Data.Linq.Table<DBCondicion_Interesado> DBCondicion_Interesado
		{
			get
			{
				return this.GetTable<DBCondicion_Interesado>();
			}
		}
		
		public System.Data.Linq.Table<DBDenegacion> DBDenegacion
		{
			get
			{
				return this.GetTable<DBDenegacion>();
			}
		}
		
		public System.Data.Linq.Table<DBInfraccion> DBInfraccion
		{
			get
			{
				return this.GetTable<DBInfraccion>();
			}
		}
		
		public System.Data.Linq.Table<DBInteresado> DBInteresado
		{
			get
			{
				return this.GetTable<DBInteresado>();
			}
		}
		
		public System.Data.Linq.Table<DBPartido> DBPartido
		{
			get
			{
				return this.GetTable<DBPartido>();
			}
		}
		
		public System.Data.Linq.Table<DBPartido_Interesado> DBPartido_Interesado
		{
			get
			{
				return this.GetTable<DBPartido_Interesado>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Infraccion_I")]
		public int Infraccion_I([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Usuario", DbType="Int")] System.Nullable<int> id_Usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Usuario);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UsuarioInteresado_Obtener")]
		public ISingleResult<UsuarioInteresado_ObtenerResult> UsuarioInteresado_Obtener([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre_Usuario", DbType="NVarChar(50)")] string nombre_Usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password_Usuario", DbType="NVarChar(50)")] string password_Usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre_Usuario, password_Usuario);
			return ((ISingleResult<UsuarioInteresado_ObtenerResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Infraccion_L")]
		public ISingleResult<Infraccion_LResult> Infraccion_L()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Infraccion_LResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ObtenerJugadoresConFuturo", IsComposable=true)]
		public object ObtenerJugadoresConFuturo()
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ObtenerJugadoresMalos")]
		public ISingleResult<ObtenerJugadoresMalosResult> ObtenerJugadoresMalos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ObtenerJugadoresMalosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Partido_Interesado_D")]
		public int Partido_Interesado_D([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Partido", DbType="Int")] System.Nullable<int> id_Partido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Interesado", DbType="Int")] System.Nullable<int> id_Interesado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Partido, id_Interesado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Partido_L")]
		public ISingleResult<Partido_LResult> Partido_L()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Partido_LResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Partido_ObtenerInteresados")]
		public ISingleResult<Partido_ObtenerInteresadosResult> Partido_ObtenerInteresados([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Partido", DbType="Int")] System.Nullable<int> id_Partido)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Partido);
			return ((ISingleResult<Partido_ObtenerInteresadosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Partido_UI")]
		public int Partido_UI([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lugar", DbType="NVarChar(50)")] string lugar, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Confirmado", DbType="Bit")] System.Nullable<bool> confirmado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha_Hora", DbType="DateTime")] System.Nullable<System.DateTime> fecha_Hora)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lugar, confirmado, fecha_Hora);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Partido_Interesado_UI")]
		public int Partido_Interesado_UI([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Partido", DbType="Int")] System.Nullable<int> id_Partido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Interesado", DbType="Int")] System.Nullable<int> id_Interesado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo_Jugador", DbType="NVarChar(50)")] string tipo_Jugador, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Baja", DbType="Bit")] System.Nullable<bool> baja)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Partido, id_Interesado, tipo_Jugador, baja);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Usuario_L")]
		public ISingleResult<Usuario_LResult> Usuario_L()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Usuario_LResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Usuario_UI")]
		public int Usuario_UI([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre_Usuario", DbType="NVarChar(50)")] string nombre_Usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password_Usuario", DbType="NVarChar(50)")] string password_Usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario_Administrador", DbType="Bit")] System.Nullable<bool> usuario_Administrador)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre_Usuario, password_Usuario, usuario_Administrador);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Partido_Interesado_L")]
		public ISingleResult<Partido_Interesado_LResult> Partido_Interesado_L([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Partido", DbType="Int")] System.Nullable<int> id_Partido)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Partido);
			return ((ISingleResult<Partido_Interesado_LResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Interesado_UI")]
		public int Interesado_UI([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Usuario", DbType="Int")] System.Nullable<int> id_Usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="NVarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="NVarChar(50)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Edad", DbType="Int")] System.Nullable<int> edad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mail", DbType="NVarChar(50)")] string mail, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Posicion", DbType="Int")] System.Nullable<int> posicion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Handicap", DbType="Int")] System.Nullable<int> handicap, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Criterio", DbType="NVarChar(50)")] string criterio)
		{
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Usuario, nombre, apellido, edad, mail, posicion, handicap, criterio);
            return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DBAmigos")]
	public partial class DBAmigos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Interesado;
		
		private int _Id_Amigo;
		
		private EntityRef<DBInteresado> _DBInteresado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_InteresadoChanging(int value);
    partial void OnId_InteresadoChanged();
    partial void OnId_AmigoChanging(int value);
    partial void OnId_AmigoChanged();
    #endregion
		
		public DBAmigos()
		{
			this._DBInteresado = default(EntityRef<DBInteresado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Interesado", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_Interesado
		{
			get
			{
				return this._Id_Interesado;
			}
			set
			{
				if ((this._Id_Interesado != value))
				{
					if (this._DBInteresado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_InteresadoChanging(value);
					this.SendPropertyChanging();
					this._Id_Interesado = value;
					this.SendPropertyChanged("Id_Interesado");
					this.OnId_InteresadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Amigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Amigo
		{
			get
			{
				return this._Id_Amigo;
			}
			set
			{
				if ((this._Id_Amigo != value))
				{
					this.OnId_AmigoChanging(value);
					this.SendPropertyChanging();
					this._Id_Amigo = value;
					this.SendPropertyChanged("Id_Amigo");
					this.OnId_AmigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DBInteresado_DBAmigos", Storage="_DBInteresado", ThisKey="Id_Interesado", OtherKey="Id_Interesado", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public DBInteresado DBInteresado
		{
			get
			{
				return this._DBInteresado.Entity;
			}
			set
			{
				DBInteresado previousValue = this._DBInteresado.Entity;
				if (((previousValue != value) 
							|| (this._DBInteresado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DBInteresado.Entity = null;
						previousValue.DBAmigos.Remove(this);
					}
					this._DBInteresado.Entity = value;
					if ((value != null))
					{
						value.DBAmigos.Add(this);
						this._Id_Interesado = value.Id_Interesado;
					}
					else
					{
						this._Id_Interesado = default(int);
					}
					this.SendPropertyChanged("DBInteresado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DBUsuario")]
	public partial class DBUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Usuario;
		
		private string _Nombre_Usuario;
		
		private string _Password_Usuario;
		
		private System.Nullable<bool> _Usuario_Administrador;
		
		private EntitySet<DBDenegacion> _DBDenegacion;
		
		private EntitySet<DBInfraccion> _DBInfraccion;
		
		private EntitySet<DBInteresado> _DBInteresado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_UsuarioChanging(int value);
    partial void OnId_UsuarioChanged();
    partial void OnNombre_UsuarioChanging(string value);
    partial void OnNombre_UsuarioChanged();
    partial void OnPassword_UsuarioChanging(string value);
    partial void OnPassword_UsuarioChanged();
    partial void OnUsuario_AdministradorChanging(System.Nullable<bool> value);
    partial void OnUsuario_AdministradorChanged();
    #endregion
		
		public DBUsuario()
		{
			this._DBDenegacion = new EntitySet<DBDenegacion>(new Action<DBDenegacion>(this.attach_DBDenegacion), new Action<DBDenegacion>(this.detach_DBDenegacion));
			this._DBInfraccion = new EntitySet<DBInfraccion>(new Action<DBInfraccion>(this.attach_DBInfraccion), new Action<DBInfraccion>(this.detach_DBInfraccion));
			this._DBInteresado = new EntitySet<DBInteresado>(new Action<DBInteresado>(this.attach_DBInteresado), new Action<DBInteresado>(this.detach_DBInteresado));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Usuario
		{
			get
			{
				return this._Id_Usuario;
			}
			set
			{
				if ((this._Id_Usuario != value))
				{
					this.OnId_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Id_Usuario = value;
					this.SendPropertyChanged("Id_Usuario");
					this.OnId_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Usuario", DbType="NVarChar(50)")]
		public string Nombre_Usuario
		{
			get
			{
				return this._Nombre_Usuario;
			}
			set
			{
				if ((this._Nombre_Usuario != value))
				{
					this.OnNombre_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Usuario = value;
					this.SendPropertyChanged("Nombre_Usuario");
					this.OnNombre_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password_Usuario", DbType="NVarChar(50)")]
		public string Password_Usuario
		{
			get
			{
				return this._Password_Usuario;
			}
			set
			{
				if ((this._Password_Usuario != value))
				{
					this.OnPassword_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Password_Usuario = value;
					this.SendPropertyChanged("Password_Usuario");
					this.OnPassword_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_Administrador", DbType="Bit")]
		public System.Nullable<bool> Usuario_Administrador
		{
			get
			{
				return this._Usuario_Administrador;
			}
			set
			{
				if ((this._Usuario_Administrador != value))
				{
					this.OnUsuario_AdministradorChanging(value);
					this.SendPropertyChanging();
					this._Usuario_Administrador = value;
					this.SendPropertyChanged("Usuario_Administrador");
					this.OnUsuario_AdministradorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DBUsuario_DBDenegacion", Storage="_DBDenegacion", ThisKey="Id_Usuario", OtherKey="Id_Usuario")]
		public EntitySet<DBDenegacion> DBDenegacion
		{
			get
			{
				return this._DBDenegacion;
			}
			set
			{
				this._DBDenegacion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DBUsuario_DBInfraccion", Storage="_DBInfraccion", ThisKey="Id_Usuario", OtherKey="Id_Usuario")]
		public EntitySet<DBInfraccion> DBInfraccion
		{
			get
			{
				return this._DBInfraccion;
			}
			set
			{
				this._DBInfraccion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DBUsuario_DBInteresado", Storage="_DBInteresado", ThisKey="Id_Usuario", OtherKey="Id_Usuario")]
		public EntitySet<DBInteresado> DBInteresado
		{
			get
			{
				return this._DBInteresado;
			}
			set
			{
				this._DBInteresado.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DBDenegacion(DBDenegacion entity)
		{
			this.SendPropertyChanging();
			entity.DBUsuario = this;
		}
		
		private void detach_DBDenegacion(DBDenegacion entity)
		{
			this.SendPropertyChanging();
			entity.DBUsuario = null;
		}
		
		private void attach_DBInfraccion(DBInfraccion entity)
		{
			this.SendPropertyChanging();
			entity.DBUsuario = this;
		}
		
		private void detach_DBInfraccion(DBInfraccion entity)
		{
			this.SendPropertyChanging();
			entity.DBUsuario = null;
		}
		
		private void attach_DBInteresado(DBInteresado entity)
		{
			this.SendPropertyChanging();
			entity.DBUsuario = this;
		}
		
		private void detach_DBInteresado(DBInteresado entity)
		{
			this.SendPropertyChanging();
			entity.DBUsuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DBCalificacion")]
	public partial class DBCalificacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Calificacion;
		
		private int _Id_Partido;
		
		private string _Descripcion;
		
		private System.Nullable<int> _Id_Jugador_Critico;
		
		private System.Nullable<int> _Id_Jugador_Criticado;
		
		private EntityRef<DBPartido> _DBPartido;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_CalificacionChanging(int value);
    partial void OnId_CalificacionChanged();
    partial void OnId_PartidoChanging(int value);
    partial void OnId_PartidoChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnId_Jugador_CriticoChanging(System.Nullable<int> value);
    partial void OnId_Jugador_CriticoChanged();
    partial void OnId_Jugador_CriticadoChanging(System.Nullable<int> value);
    partial void OnId_Jugador_CriticadoChanged();
    #endregion
		
		public DBCalificacion()
		{
			this._DBPartido = default(EntityRef<DBPartido>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Calificacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Calificacion
		{
			get
			{
				return this._Id_Calificacion;
			}
			set
			{
				if ((this._Id_Calificacion != value))
				{
					this.OnId_CalificacionChanging(value);
					this.SendPropertyChanging();
					this._Id_Calificacion = value;
					this.SendPropertyChanged("Id_Calificacion");
					this.OnId_CalificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Partido", DbType="Int NOT NULL")]
		public int Id_Partido
		{
			get
			{
				return this._Id_Partido;
			}
			set
			{
				if ((this._Id_Partido != value))
				{
					if (this._DBPartido.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_PartidoChanging(value);
					this.SendPropertyChanging();
					this._Id_Partido = value;
					this.SendPropertyChanged("Id_Partido");
					this.OnId_PartidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Jugador_Critico", DbType="Int")]
		public System.Nullable<int> Id_Jugador_Critico
		{
			get
			{
				return this._Id_Jugador_Critico;
			}
			set
			{
				if ((this._Id_Jugador_Critico != value))
				{
					this.OnId_Jugador_CriticoChanging(value);
					this.SendPropertyChanging();
					this._Id_Jugador_Critico = value;
					this.SendPropertyChanged("Id_Jugador_Critico");
					this.OnId_Jugador_CriticoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Jugador_Criticado", DbType="Int")]
		public System.Nullable<int> Id_Jugador_Criticado
		{
			get
			{
				return this._Id_Jugador_Criticado;
			}
			set
			{
				if ((this._Id_Jugador_Criticado != value))
				{
					this.OnId_Jugador_CriticadoChanging(value);
					this.SendPropertyChanging();
					this._Id_Jugador_Criticado = value;
					this.SendPropertyChanged("Id_Jugador_Criticado");
					this.OnId_Jugador_CriticadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DBPartido_DBCalificacion", Storage="_DBPartido", ThisKey="Id_Partido", OtherKey="Id_Partido", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public DBPartido DBPartido
		{
			get
			{
				return this._DBPartido.Entity;
			}
			set
			{
				DBPartido previousValue = this._DBPartido.Entity;
				if (((previousValue != value) 
							|| (this._DBPartido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DBPartido.Entity = null;
						previousValue.DBCalificacion.Remove(this);
					}
					this._DBPartido.Entity = value;
					if ((value != null))
					{
						value.DBCalificacion.Add(this);
						this._Id_Partido = value.Id_Partido;
					}
					else
					{
						this._Id_Partido = default(int);
					}
					this.SendPropertyChanged("DBPartido");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DBCondicion")]
	public partial class DBCondicion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Condicion;
		
		private string _Descripcion_Condicion;
		
		private EntitySet<DBCondicion_Interesado> _DBCondicion_Interesado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_CondicionChanging(int value);
    partial void OnId_CondicionChanged();
    partial void OnDescripcion_CondicionChanging(string value);
    partial void OnDescripcion_CondicionChanged();
    #endregion
		
		public DBCondicion()
		{
			this._DBCondicion_Interesado = new EntitySet<DBCondicion_Interesado>(new Action<DBCondicion_Interesado>(this.attach_DBCondicion_Interesado), new Action<DBCondicion_Interesado>(this.detach_DBCondicion_Interesado));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Condicion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Condicion
		{
			get
			{
				return this._Id_Condicion;
			}
			set
			{
				if ((this._Id_Condicion != value))
				{
					this.OnId_CondicionChanging(value);
					this.SendPropertyChanging();
					this._Id_Condicion = value;
					this.SendPropertyChanged("Id_Condicion");
					this.OnId_CondicionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion_Condicion", DbType="NVarChar(50)")]
		public string Descripcion_Condicion
		{
			get
			{
				return this._Descripcion_Condicion;
			}
			set
			{
				if ((this._Descripcion_Condicion != value))
				{
					this.OnDescripcion_CondicionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion_Condicion = value;
					this.SendPropertyChanged("Descripcion_Condicion");
					this.OnDescripcion_CondicionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DBCondicion_DBCondicion_Interesado", Storage="_DBCondicion_Interesado", ThisKey="Id_Condicion", OtherKey="Id_Condicion")]
		public EntitySet<DBCondicion_Interesado> DBCondicion_Interesado
		{
			get
			{
				return this._DBCondicion_Interesado;
			}
			set
			{
				this._DBCondicion_Interesado.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DBCondicion_Interesado(DBCondicion_Interesado entity)
		{
			this.SendPropertyChanging();
			entity.DBCondicion = this;
		}
		
		private void detach_DBCondicion_Interesado(DBCondicion_Interesado entity)
		{
			this.SendPropertyChanging();
			entity.DBCondicion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DBCondicion_Interesado")]
	public partial class DBCondicion_Interesado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Condicion;
		
		private int _Id_interesado;
		
		private EntityRef<DBCondicion> _DBCondicion;
		
		private EntityRef<DBInteresado> _DBInteresado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_CondicionChanging(int value);
    partial void OnId_CondicionChanged();
    partial void OnId_interesadoChanging(int value);
    partial void OnId_interesadoChanged();
    #endregion
		
		public DBCondicion_Interesado()
		{
			this._DBCondicion = default(EntityRef<DBCondicion>);
			this._DBInteresado = default(EntityRef<DBInteresado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Condicion", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_Condicion
		{
			get
			{
				return this._Id_Condicion;
			}
			set
			{
				if ((this._Id_Condicion != value))
				{
					if (this._DBCondicion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_CondicionChanging(value);
					this.SendPropertyChanging();
					this._Id_Condicion = value;
					this.SendPropertyChanged("Id_Condicion");
					this.OnId_CondicionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_interesado", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_interesado
		{
			get
			{
				return this._Id_interesado;
			}
			set
			{
				if ((this._Id_interesado != value))
				{
					if (this._DBInteresado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_interesadoChanging(value);
					this.SendPropertyChanging();
					this._Id_interesado = value;
					this.SendPropertyChanged("Id_interesado");
					this.OnId_interesadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DBCondicion_DBCondicion_Interesado", Storage="_DBCondicion", ThisKey="Id_Condicion", OtherKey="Id_Condicion", IsForeignKey=true)]
		public DBCondicion DBCondicion
		{
			get
			{
				return this._DBCondicion.Entity;
			}
			set
			{
				DBCondicion previousValue = this._DBCondicion.Entity;
				if (((previousValue != value) 
							|| (this._DBCondicion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DBCondicion.Entity = null;
						previousValue.DBCondicion_Interesado.Remove(this);
					}
					this._DBCondicion.Entity = value;
					if ((value != null))
					{
						value.DBCondicion_Interesado.Add(this);
						this._Id_Condicion = value.Id_Condicion;
					}
					else
					{
						this._Id_Condicion = default(int);
					}
					this.SendPropertyChanged("DBCondicion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DBInteresado_DBCondicion_Interesado", Storage="_DBInteresado", ThisKey="Id_interesado", OtherKey="Id_Interesado", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public DBInteresado DBInteresado
		{
			get
			{
				return this._DBInteresado.Entity;
			}
			set
			{
				DBInteresado previousValue = this._DBInteresado.Entity;
				if (((previousValue != value) 
							|| (this._DBInteresado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DBInteresado.Entity = null;
						previousValue.DBCondicion_Interesado.Remove(this);
					}
					this._DBInteresado.Entity = value;
					if ((value != null))
					{
						value.DBCondicion_Interesado.Add(this);
						this._Id_interesado = value.Id_Interesado;
					}
					else
					{
						this._Id_interesado = default(int);
					}
					this.SendPropertyChanged("DBInteresado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DBDenegacion")]
	public partial class DBDenegacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Denegacion;
		
		private int _Id_Interesado;
		
		private int _Id_Usuario;
		
		private System.Nullable<System.DateTime> _Fecha_Denegacion;
		
		private string _Descripcion_motivo_Denegacion;
		
		private System.Nullable<int> _Id_Admin;
		
		private EntityRef<DBUsuario> _DBUsuario;
		
		private EntityRef<DBInteresado> _DBInteresado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_DenegacionChanging(int value);
    partial void OnId_DenegacionChanged();
    partial void OnId_InteresadoChanging(int value);
    partial void OnId_InteresadoChanged();
    partial void OnId_UsuarioChanging(int value);
    partial void OnId_UsuarioChanged();
    partial void OnFecha_DenegacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_DenegacionChanged();
    partial void OnDescripcion_motivo_DenegacionChanging(string value);
    partial void OnDescripcion_motivo_DenegacionChanged();
    partial void OnId_AdminChanging(System.Nullable<int> value);
    partial void OnId_AdminChanged();
    #endregion
		
		public DBDenegacion()
		{
			this._DBUsuario = default(EntityRef<DBUsuario>);
			this._DBInteresado = default(EntityRef<DBInteresado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Denegacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Denegacion
		{
			get
			{
				return this._Id_Denegacion;
			}
			set
			{
				if ((this._Id_Denegacion != value))
				{
					this.OnId_DenegacionChanging(value);
					this.SendPropertyChanging();
					this._Id_Denegacion = value;
					this.SendPropertyChanged("Id_Denegacion");
					this.OnId_DenegacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Interesado", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_Interesado
		{
			get
			{
				return this._Id_Interesado;
			}
			set
			{
				if ((this._Id_Interesado != value))
				{
					if (this._DBInteresado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_InteresadoChanging(value);
					this.SendPropertyChanging();
					this._Id_Interesado = value;
					this.SendPropertyChanged("Id_Interesado");
					this.OnId_InteresadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Usuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_Usuario
		{
			get
			{
				return this._Id_Usuario;
			}
			set
			{
				if ((this._Id_Usuario != value))
				{
					if (this._DBUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Id_Usuario = value;
					this.SendPropertyChanged("Id_Usuario");
					this.OnId_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Denegacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Denegacion
		{
			get
			{
				return this._Fecha_Denegacion;
			}
			set
			{
				if ((this._Fecha_Denegacion != value))
				{
					this.OnFecha_DenegacionChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Denegacion = value;
					this.SendPropertyChanged("Fecha_Denegacion");
					this.OnFecha_DenegacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion_motivo_Denegacion", DbType="NVarChar(50)")]
		public string Descripcion_motivo_Denegacion
		{
			get
			{
				return this._Descripcion_motivo_Denegacion;
			}
			set
			{
				if ((this._Descripcion_motivo_Denegacion != value))
				{
					this.OnDescripcion_motivo_DenegacionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion_motivo_Denegacion = value;
					this.SendPropertyChanged("Descripcion_motivo_Denegacion");
					this.OnDescripcion_motivo_DenegacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Admin", DbType="Int")]
		public System.Nullable<int> Id_Admin
		{
			get
			{
				return this._Id_Admin;
			}
			set
			{
				if ((this._Id_Admin != value))
				{
					this.OnId_AdminChanging(value);
					this.SendPropertyChanging();
					this._Id_Admin = value;
					this.SendPropertyChanged("Id_Admin");
					this.OnId_AdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DBUsuario_DBDenegacion", Storage="_DBUsuario", ThisKey="Id_Usuario", OtherKey="Id_Usuario", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public DBUsuario DBUsuario
		{
			get
			{
				return this._DBUsuario.Entity;
			}
			set
			{
				DBUsuario previousValue = this._DBUsuario.Entity;
				if (((previousValue != value) 
							|| (this._DBUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DBUsuario.Entity = null;
						previousValue.DBDenegacion.Remove(this);
					}
					this._DBUsuario.Entity = value;
					if ((value != null))
					{
						value.DBDenegacion.Add(this);
						this._Id_Usuario = value.Id_Usuario;
					}
					else
					{
						this._Id_Usuario = default(int);
					}
					this.SendPropertyChanged("DBUsuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DBInteresado_DBDenegacion", Storage="_DBInteresado", ThisKey="Id_Interesado", OtherKey="Id_Interesado", IsForeignKey=true)]
		public DBInteresado DBInteresado
		{
			get
			{
				return this._DBInteresado.Entity;
			}
			set
			{
				DBInteresado previousValue = this._DBInteresado.Entity;
				if (((previousValue != value) 
							|| (this._DBInteresado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DBInteresado.Entity = null;
						previousValue.DBDenegacion.Remove(this);
					}
					this._DBInteresado.Entity = value;
					if ((value != null))
					{
						value.DBDenegacion.Add(this);
						this._Id_Interesado = value.Id_Interesado;
					}
					else
					{
						this._Id_Interesado = default(int);
					}
					this.SendPropertyChanged("DBInteresado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DBInfraccion")]
	public partial class DBInfraccion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Infraccion;
		
		private string _Descripcion_Infraccion;
		
		private System.Nullable<int> _Id_Usuario;
		
		private EntityRef<DBUsuario> _DBUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_InfraccionChanging(int value);
    partial void OnId_InfraccionChanged();
    partial void OnDescripcion_InfraccionChanging(string value);
    partial void OnDescripcion_InfraccionChanged();
    partial void OnId_UsuarioChanging(System.Nullable<int> value);
    partial void OnId_UsuarioChanged();
    #endregion
		
		public DBInfraccion()
		{
			this._DBUsuario = default(EntityRef<DBUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Infraccion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Infraccion
		{
			get
			{
				return this._Id_Infraccion;
			}
			set
			{
				if ((this._Id_Infraccion != value))
				{
					this.OnId_InfraccionChanging(value);
					this.SendPropertyChanging();
					this._Id_Infraccion = value;
					this.SendPropertyChanged("Id_Infraccion");
					this.OnId_InfraccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion_Infraccion", DbType="NVarChar(50)")]
		public string Descripcion_Infraccion
		{
			get
			{
				return this._Descripcion_Infraccion;
			}
			set
			{
				if ((this._Descripcion_Infraccion != value))
				{
					this.OnDescripcion_InfraccionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion_Infraccion = value;
					this.SendPropertyChanged("Descripcion_Infraccion");
					this.OnDescripcion_InfraccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Usuario", DbType="Int")]
		public System.Nullable<int> Id_Usuario
		{
			get
			{
				return this._Id_Usuario;
			}
			set
			{
				if ((this._Id_Usuario != value))
				{
					if (this._DBUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Id_Usuario = value;
					this.SendPropertyChanged("Id_Usuario");
					this.OnId_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DBUsuario_DBInfraccion", Storage="_DBUsuario", ThisKey="Id_Usuario", OtherKey="Id_Usuario", IsForeignKey=true, DeleteRule="CASCADE")]
		public DBUsuario DBUsuario
		{
			get
			{
				return this._DBUsuario.Entity;
			}
			set
			{
				DBUsuario previousValue = this._DBUsuario.Entity;
				if (((previousValue != value) 
							|| (this._DBUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DBUsuario.Entity = null;
						previousValue.DBInfraccion.Remove(this);
					}
					this._DBUsuario.Entity = value;
					if ((value != null))
					{
						value.DBInfraccion.Add(this);
						this._Id_Usuario = value.Id_Usuario;
					}
					else
					{
						this._Id_Usuario = default(Nullable<int>);
					}
					this.SendPropertyChanged("DBUsuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DBInteresado")]
	public partial class DBInteresado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Interesado;
		
		private int _Id_Usuario;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private System.Nullable<int> _Edad;
		
		private string _Mail;
		
		private System.Nullable<int> _Posicion;
		
		private System.Nullable<int> _Handicap;
		
		private string _Criterio;
		
		private int _CantPartidosJugados;
		
		private EntitySet<DBAmigos> _DBAmigos;
		
		private EntitySet<DBCondicion_Interesado> _DBCondicion_Interesado;
		
		private EntitySet<DBDenegacion> _DBDenegacion;
		
		private EntitySet<DBPartido_Interesado> _DBPartido_Interesado;
		
		private EntityRef<DBUsuario> _DBUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_InteresadoChanging(int value);
    partial void OnId_InteresadoChanged();
    partial void OnId_UsuarioChanging(int value);
    partial void OnId_UsuarioChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnEdadChanging(System.Nullable<int> value);
    partial void OnEdadChanged();
    partial void OnMailChanging(string value);
    partial void OnMailChanged();
    partial void OnPosicionChanging(System.Nullable<int> value);
    partial void OnPosicionChanged();
    partial void OnHandicapChanging(System.Nullable<int> value);
    partial void OnHandicapChanged();
    partial void OnCriterioChanging(string value);
    partial void OnCriterioChanged();
    partial void OnCantPartidosJugadosChanging(int value);
    partial void OnCantPartidosJugadosChanged();
    #endregion
		
		public DBInteresado()
		{
			this._DBAmigos = new EntitySet<DBAmigos>(new Action<DBAmigos>(this.attach_DBAmigos), new Action<DBAmigos>(this.detach_DBAmigos));
			this._DBCondicion_Interesado = new EntitySet<DBCondicion_Interesado>(new Action<DBCondicion_Interesado>(this.attach_DBCondicion_Interesado), new Action<DBCondicion_Interesado>(this.detach_DBCondicion_Interesado));
			this._DBDenegacion = new EntitySet<DBDenegacion>(new Action<DBDenegacion>(this.attach_DBDenegacion), new Action<DBDenegacion>(this.detach_DBDenegacion));
			this._DBPartido_Interesado = new EntitySet<DBPartido_Interesado>(new Action<DBPartido_Interesado>(this.attach_DBPartido_Interesado), new Action<DBPartido_Interesado>(this.detach_DBPartido_Interesado));
			this._DBUsuario = default(EntityRef<DBUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Interesado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Interesado
		{
			get
			{
				return this._Id_Interesado;
			}
			set
			{
				if ((this._Id_Interesado != value))
				{
					this.OnId_InteresadoChanging(value);
					this.SendPropertyChanging();
					this._Id_Interesado = value;
					this.SendPropertyChanged("Id_Interesado");
					this.OnId_InteresadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Usuario", DbType="Int NOT NULL")]
		public int Id_Usuario
		{
			get
			{
				return this._Id_Usuario;
			}
			set
			{
				if ((this._Id_Usuario != value))
				{
					if (this._DBUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Id_Usuario = value;
					this.SendPropertyChanged("Id_Usuario");
					this.OnId_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edad", DbType="Int")]
		public System.Nullable<int> Edad
		{
			get
			{
				return this._Edad;
			}
			set
			{
				if ((this._Edad != value))
				{
					this.OnEdadChanging(value);
					this.SendPropertyChanging();
					this._Edad = value;
					this.SendPropertyChanged("Edad");
					this.OnEdadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="NVarChar(50)")]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this.OnMailChanging(value);
					this.SendPropertyChanging();
					this._Mail = value;
					this.SendPropertyChanged("Mail");
					this.OnMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Posicion", DbType="Int")]
		public System.Nullable<int> Posicion
		{
			get
			{
				return this._Posicion;
			}
			set
			{
				if ((this._Posicion != value))
				{
					this.OnPosicionChanging(value);
					this.SendPropertyChanging();
					this._Posicion = value;
					this.SendPropertyChanged("Posicion");
					this.OnPosicionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Handicap", DbType="Int")]
		public System.Nullable<int> Handicap
		{
			get
			{
				return this._Handicap;
			}
			set
			{
				if ((this._Handicap != value))
				{
					this.OnHandicapChanging(value);
					this.SendPropertyChanging();
					this._Handicap = value;
					this.SendPropertyChanged("Handicap");
					this.OnHandicapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criterio", DbType="NVarChar(50)")]
		public string Criterio
		{
			get
			{
				return this._Criterio;
			}
			set
			{
				if ((this._Criterio != value))
				{
					this.OnCriterioChanging(value);
					this.SendPropertyChanging();
					this._Criterio = value;
					this.SendPropertyChanged("Criterio");
					this.OnCriterioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantPartidosJugados", DbType="Int NOT NULL")]
		public int CantPartidosJugados
		{
			get
			{
				return this._CantPartidosJugados;
			}
			set
			{
				if ((this._CantPartidosJugados != value))
				{
					this.OnCantPartidosJugadosChanging(value);
					this.SendPropertyChanging();
					this._CantPartidosJugados = value;
					this.SendPropertyChanged("CantPartidosJugados");
					this.OnCantPartidosJugadosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DBInteresado_DBAmigos", Storage="_DBAmigos", ThisKey="Id_Interesado", OtherKey="Id_Interesado")]
		public EntitySet<DBAmigos> DBAmigos
		{
			get
			{
				return this._DBAmigos;
			}
			set
			{
				this._DBAmigos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DBInteresado_DBCondicion_Interesado", Storage="_DBCondicion_Interesado", ThisKey="Id_Interesado", OtherKey="Id_interesado")]
		public EntitySet<DBCondicion_Interesado> DBCondicion_Interesado
		{
			get
			{
				return this._DBCondicion_Interesado;
			}
			set
			{
				this._DBCondicion_Interesado.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DBInteresado_DBDenegacion", Storage="_DBDenegacion", ThisKey="Id_Interesado", OtherKey="Id_Interesado")]
		public EntitySet<DBDenegacion> DBDenegacion
		{
			get
			{
				return this._DBDenegacion;
			}
			set
			{
				this._DBDenegacion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DBInteresado_DBPartido_Interesado", Storage="_DBPartido_Interesado", ThisKey="Id_Interesado", OtherKey="Id_Interesado")]
		public EntitySet<DBPartido_Interesado> DBPartido_Interesado
		{
			get
			{
				return this._DBPartido_Interesado;
			}
			set
			{
				this._DBPartido_Interesado.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DBUsuario_DBInteresado", Storage="_DBUsuario", ThisKey="Id_Usuario", OtherKey="Id_Usuario", IsForeignKey=true)]
		public DBUsuario DBUsuario
		{
			get
			{
				return this._DBUsuario.Entity;
			}
			set
			{
				DBUsuario previousValue = this._DBUsuario.Entity;
				if (((previousValue != value) 
							|| (this._DBUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DBUsuario.Entity = null;
						previousValue.DBInteresado.Remove(this);
					}
					this._DBUsuario.Entity = value;
					if ((value != null))
					{
						value.DBInteresado.Add(this);
						this._Id_Usuario = value.Id_Usuario;
					}
					else
					{
						this._Id_Usuario = default(int);
					}
					this.SendPropertyChanged("DBUsuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DBAmigos(DBAmigos entity)
		{
			this.SendPropertyChanging();
			entity.DBInteresado = this;
		}
		
		private void detach_DBAmigos(DBAmigos entity)
		{
			this.SendPropertyChanging();
			entity.DBInteresado = null;
		}
		
		private void attach_DBCondicion_Interesado(DBCondicion_Interesado entity)
		{
			this.SendPropertyChanging();
			entity.DBInteresado = this;
		}
		
		private void detach_DBCondicion_Interesado(DBCondicion_Interesado entity)
		{
			this.SendPropertyChanging();
			entity.DBInteresado = null;
		}
		
		private void attach_DBDenegacion(DBDenegacion entity)
		{
			this.SendPropertyChanging();
			entity.DBInteresado = this;
		}
		
		private void detach_DBDenegacion(DBDenegacion entity)
		{
			this.SendPropertyChanging();
			entity.DBInteresado = null;
		}
		
		private void attach_DBPartido_Interesado(DBPartido_Interesado entity)
		{
			this.SendPropertyChanging();
			entity.DBInteresado = this;
		}
		
		private void detach_DBPartido_Interesado(DBPartido_Interesado entity)
		{
			this.SendPropertyChanging();
			entity.DBInteresado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DBPartido")]
	public partial class DBPartido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Partido;
		
		private string _Lugar;
		
		private System.Nullable<bool> _Confirmado;
		
		private System.Nullable<System.DateTime> _Fecha_Hora;
		
		private EntitySet<DBCalificacion> _DBCalificacion;
		
		private EntitySet<DBPartido_Interesado> _DBPartido_Interesado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_PartidoChanging(int value);
    partial void OnId_PartidoChanged();
    partial void OnLugarChanging(string value);
    partial void OnLugarChanged();
    partial void OnConfirmadoChanging(System.Nullable<bool> value);
    partial void OnConfirmadoChanged();
    partial void OnFecha_HoraChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_HoraChanged();
    #endregion
		
		public DBPartido()
		{
			this._DBCalificacion = new EntitySet<DBCalificacion>(new Action<DBCalificacion>(this.attach_DBCalificacion), new Action<DBCalificacion>(this.detach_DBCalificacion));
			this._DBPartido_Interesado = new EntitySet<DBPartido_Interesado>(new Action<DBPartido_Interesado>(this.attach_DBPartido_Interesado), new Action<DBPartido_Interesado>(this.detach_DBPartido_Interesado));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Partido", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Partido
		{
			get
			{
				return this._Id_Partido;
			}
			set
			{
				if ((this._Id_Partido != value))
				{
					this.OnId_PartidoChanging(value);
					this.SendPropertyChanging();
					this._Id_Partido = value;
					this.SendPropertyChanged("Id_Partido");
					this.OnId_PartidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lugar", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Lugar
		{
			get
			{
				return this._Lugar;
			}
			set
			{
				if ((this._Lugar != value))
				{
					this.OnLugarChanging(value);
					this.SendPropertyChanging();
					this._Lugar = value;
					this.SendPropertyChanged("Lugar");
					this.OnLugarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Confirmado", DbType="Bit")]
		public System.Nullable<bool> Confirmado
		{
			get
			{
				return this._Confirmado;
			}
			set
			{
				if ((this._Confirmado != value))
				{
					this.OnConfirmadoChanging(value);
					this.SendPropertyChanging();
					this._Confirmado = value;
					this.SendPropertyChanged("Confirmado");
					this.OnConfirmadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Hora", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Hora
		{
			get
			{
				return this._Fecha_Hora;
			}
			set
			{
				if ((this._Fecha_Hora != value))
				{
					this.OnFecha_HoraChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Hora = value;
					this.SendPropertyChanged("Fecha_Hora");
					this.OnFecha_HoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DBPartido_DBCalificacion", Storage="_DBCalificacion", ThisKey="Id_Partido", OtherKey="Id_Partido")]
		public EntitySet<DBCalificacion> DBCalificacion
		{
			get
			{
				return this._DBCalificacion;
			}
			set
			{
				this._DBCalificacion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DBPartido_DBPartido_Interesado", Storage="_DBPartido_Interesado", ThisKey="Id_Partido", OtherKey="Id_Partido")]
		public EntitySet<DBPartido_Interesado> DBPartido_Interesado
		{
			get
			{
				return this._DBPartido_Interesado;
			}
			set
			{
				this._DBPartido_Interesado.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DBCalificacion(DBCalificacion entity)
		{
			this.SendPropertyChanging();
			entity.DBPartido = this;
		}
		
		private void detach_DBCalificacion(DBCalificacion entity)
		{
			this.SendPropertyChanging();
			entity.DBPartido = null;
		}
		
		private void attach_DBPartido_Interesado(DBPartido_Interesado entity)
		{
			this.SendPropertyChanging();
			entity.DBPartido = this;
		}
		
		private void detach_DBPartido_Interesado(DBPartido_Interesado entity)
		{
			this.SendPropertyChanging();
			entity.DBPartido = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DBPartido_Interesado")]
	public partial class DBPartido_Interesado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Partido;
		
		private int _Id_Interesado;
		
		private string _Tipo_Jugador;
		
		private System.Nullable<bool> _Baja;
		
		private EntityRef<DBInteresado> _DBInteresado;
		
		private EntityRef<DBPartido> _DBPartido;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_PartidoChanging(int value);
    partial void OnId_PartidoChanged();
    partial void OnId_InteresadoChanging(int value);
    partial void OnId_InteresadoChanged();
    partial void OnTipo_JugadorChanging(string value);
    partial void OnTipo_JugadorChanged();
    partial void OnBajaChanging(System.Nullable<bool> value);
    partial void OnBajaChanged();
    #endregion
		
		public DBPartido_Interesado()
		{
			this._DBInteresado = default(EntityRef<DBInteresado>);
			this._DBPartido = default(EntityRef<DBPartido>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Partido", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_Partido
		{
			get
			{
				return this._Id_Partido;
			}
			set
			{
				if ((this._Id_Partido != value))
				{
					if (this._DBPartido.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_PartidoChanging(value);
					this.SendPropertyChanging();
					this._Id_Partido = value;
					this.SendPropertyChanged("Id_Partido");
					this.OnId_PartidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Interesado", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_Interesado
		{
			get
			{
				return this._Id_Interesado;
			}
			set
			{
				if ((this._Id_Interesado != value))
				{
					if (this._DBInteresado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_InteresadoChanging(value);
					this.SendPropertyChanging();
					this._Id_Interesado = value;
					this.SendPropertyChanged("Id_Interesado");
					this.OnId_InteresadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo_Jugador", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tipo_Jugador
		{
			get
			{
				return this._Tipo_Jugador;
			}
			set
			{
				if ((this._Tipo_Jugador != value))
				{
					this.OnTipo_JugadorChanging(value);
					this.SendPropertyChanging();
					this._Tipo_Jugador = value;
					this.SendPropertyChanged("Tipo_Jugador");
					this.OnTipo_JugadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Baja", DbType="Bit")]
		public System.Nullable<bool> Baja
		{
			get
			{
				return this._Baja;
			}
			set
			{
				if ((this._Baja != value))
				{
					this.OnBajaChanging(value);
					this.SendPropertyChanging();
					this._Baja = value;
					this.SendPropertyChanged("Baja");
					this.OnBajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DBInteresado_DBPartido_Interesado", Storage="_DBInteresado", ThisKey="Id_Interesado", OtherKey="Id_Interesado", IsForeignKey=true)]
		public DBInteresado DBInteresado
		{
			get
			{
				return this._DBInteresado.Entity;
			}
			set
			{
				DBInteresado previousValue = this._DBInteresado.Entity;
				if (((previousValue != value) 
							|| (this._DBInteresado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DBInteresado.Entity = null;
						previousValue.DBPartido_Interesado.Remove(this);
					}
					this._DBInteresado.Entity = value;
					if ((value != null))
					{
						value.DBPartido_Interesado.Add(this);
						this._Id_Interesado = value.Id_Interesado;
					}
					else
					{
						this._Id_Interesado = default(int);
					}
					this.SendPropertyChanged("DBInteresado");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DBPartido_DBPartido_Interesado", Storage="_DBPartido", ThisKey="Id_Partido", OtherKey="Id_Partido", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public DBPartido DBPartido
		{
			get
			{
				return this._DBPartido.Entity;
			}
			set
			{
				DBPartido previousValue = this._DBPartido.Entity;
				if (((previousValue != value) 
							|| (this._DBPartido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DBPartido.Entity = null;
						previousValue.DBPartido_Interesado.Remove(this);
					}
					this._DBPartido.Entity = value;
					if ((value != null))
					{
						value.DBPartido_Interesado.Add(this);
						this._Id_Partido = value.Id_Partido;
					}
					else
					{
						this._Id_Partido = default(int);
					}
					this.SendPropertyChanged("DBPartido");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class UsuarioInteresado_ObtenerResult
	{
		
		private string _Nombre_Usuario;
		
		private string _Password_Usuario;
		
		private int _Id_Usuario;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private System.Nullable<int> _Edad;
		
		private string _Mail;
		
		private System.Nullable<int> _Posicion;
		
		private System.Nullable<int> _Handicap;
		
		private string _Criterio;
		
		private int _CantPartidosJugados;
		
		public UsuarioInteresado_ObtenerResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Usuario", DbType="NVarChar(50)")]
		public string Nombre_Usuario
		{
			get
			{
				return this._Nombre_Usuario;
			}
			set
			{
				if ((this._Nombre_Usuario != value))
				{
					this._Nombre_Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password_Usuario", DbType="NVarChar(50)")]
		public string Password_Usuario
		{
			get
			{
				return this._Password_Usuario;
			}
			set
			{
				if ((this._Password_Usuario != value))
				{
					this._Password_Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Usuario", DbType="Int NOT NULL")]
		public int Id_Usuario
		{
			get
			{
				return this._Id_Usuario;
			}
			set
			{
				if ((this._Id_Usuario != value))
				{
					this._Id_Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edad", DbType="Int")]
		public System.Nullable<int> Edad
		{
			get
			{
				return this._Edad;
			}
			set
			{
				if ((this._Edad != value))
				{
					this._Edad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="NVarChar(50)")]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this._Mail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Posicion", DbType="Int")]
		public System.Nullable<int> Posicion
		{
			get
			{
				return this._Posicion;
			}
			set
			{
				if ((this._Posicion != value))
				{
					this._Posicion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Handicap", DbType="Int")]
		public System.Nullable<int> Handicap
		{
			get
			{
				return this._Handicap;
			}
			set
			{
				if ((this._Handicap != value))
				{
					this._Handicap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criterio", DbType="NVarChar(50)")]
		public string Criterio
		{
			get
			{
				return this._Criterio;
			}
			set
			{
				if ((this._Criterio != value))
				{
					this._Criterio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantPartidosJugados", DbType="Int NOT NULL")]
		public int CantPartidosJugados
		{
			get
			{
				return this._CantPartidosJugados;
			}
			set
			{
				if ((this._CantPartidosJugados != value))
				{
					this._CantPartidosJugados = value;
				}
			}
		}
	}
	
	public partial class Infraccion_LResult
	{
		
		private string _Nombre_Usuario;
		
		private string _Password_Usuario;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private System.Nullable<int> _Edad;
		
		private string _Mail;
		
		private System.Nullable<int> _Posicion;
		
		private System.Nullable<int> _Handicap;
		
		private int _CantPartidosJugados;
		
		public Infraccion_LResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Usuario", DbType="NVarChar(50)")]
		public string Nombre_Usuario
		{
			get
			{
				return this._Nombre_Usuario;
			}
			set
			{
				if ((this._Nombre_Usuario != value))
				{
					this._Nombre_Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password_Usuario", DbType="NVarChar(50)")]
		public string Password_Usuario
		{
			get
			{
				return this._Password_Usuario;
			}
			set
			{
				if ((this._Password_Usuario != value))
				{
					this._Password_Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edad", DbType="Int")]
		public System.Nullable<int> Edad
		{
			get
			{
				return this._Edad;
			}
			set
			{
				if ((this._Edad != value))
				{
					this._Edad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="NVarChar(50)")]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this._Mail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Posicion", DbType="Int")]
		public System.Nullable<int> Posicion
		{
			get
			{
				return this._Posicion;
			}
			set
			{
				if ((this._Posicion != value))
				{
					this._Posicion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Handicap", DbType="Int")]
		public System.Nullable<int> Handicap
		{
			get
			{
				return this._Handicap;
			}
			set
			{
				if ((this._Handicap != value))
				{
					this._Handicap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantPartidosJugados", DbType="Int NOT NULL")]
		public int CantPartidosJugados
		{
			get
			{
				return this._CantPartidosJugados;
			}
			set
			{
				if ((this._CantPartidosJugados != value))
				{
					this._CantPartidosJugados = value;
				}
			}
		}
	}
	
	public partial class ObtenerJugadoresMalosResult
	{
		
		private int _Id_Interesado;
		
		private int _Id_Usuario;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private System.Nullable<int> _Edad;
		
		private System.Nullable<int> _Posicion;
		
		private string _Mail;
		
		private System.Nullable<int> _Handicap;
		
		private int _CantPartidosJugados;
		
		public ObtenerJugadoresMalosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Interesado", DbType="Int NOT NULL")]
		public int Id_Interesado
		{
			get
			{
				return this._Id_Interesado;
			}
			set
			{
				if ((this._Id_Interesado != value))
				{
					this._Id_Interesado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Usuario", DbType="Int NOT NULL")]
		public int Id_Usuario
		{
			get
			{
				return this._Id_Usuario;
			}
			set
			{
				if ((this._Id_Usuario != value))
				{
					this._Id_Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edad", DbType="Int")]
		public System.Nullable<int> Edad
		{
			get
			{
				return this._Edad;
			}
			set
			{
				if ((this._Edad != value))
				{
					this._Edad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Posicion", DbType="Int")]
		public System.Nullable<int> Posicion
		{
			get
			{
				return this._Posicion;
			}
			set
			{
				if ((this._Posicion != value))
				{
					this._Posicion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="NVarChar(50)")]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this._Mail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Handicap", DbType="Int")]
		public System.Nullable<int> Handicap
		{
			get
			{
				return this._Handicap;
			}
			set
			{
				if ((this._Handicap != value))
				{
					this._Handicap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantPartidosJugados", DbType="Int NOT NULL")]
		public int CantPartidosJugados
		{
			get
			{
				return this._CantPartidosJugados;
			}
			set
			{
				if ((this._CantPartidosJugados != value))
				{
					this._CantPartidosJugados = value;
				}
			}
		}
	}
	
	public partial class Partido_LResult
	{
		
		private string _Lugar;
		
		private System.Nullable<System.DateTime> _Fecha_Hora;
		
		private System.Nullable<bool> _Confirmado;
		
		public Partido_LResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lugar", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Lugar
		{
			get
			{
				return this._Lugar;
			}
			set
			{
				if ((this._Lugar != value))
				{
					this._Lugar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Hora", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Hora
		{
			get
			{
				return this._Fecha_Hora;
			}
			set
			{
				if ((this._Fecha_Hora != value))
				{
					this._Fecha_Hora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Confirmado", DbType="Bit")]
		public System.Nullable<bool> Confirmado
		{
			get
			{
				return this._Confirmado;
			}
			set
			{
				if ((this._Confirmado != value))
				{
					this._Confirmado = value;
				}
			}
		}
	}
	
	public partial class Partido_ObtenerInteresadosResult
	{
		
		private string _Nombre_Usuario;
		
		private string _Password_Usuario;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private System.Nullable<int> _Edad;
		
		private string _Mail;
		
		private System.Nullable<int> _Posicion;
		
		private System.Nullable<int> _Handicap;
		
		private int _CantPartidosJugados;
		
		public Partido_ObtenerInteresadosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Usuario", DbType="NVarChar(50)")]
		public string Nombre_Usuario
		{
			get
			{
				return this._Nombre_Usuario;
			}
			set
			{
				if ((this._Nombre_Usuario != value))
				{
					this._Nombre_Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password_Usuario", DbType="NVarChar(50)")]
		public string Password_Usuario
		{
			get
			{
				return this._Password_Usuario;
			}
			set
			{
				if ((this._Password_Usuario != value))
				{
					this._Password_Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edad", DbType="Int")]
		public System.Nullable<int> Edad
		{
			get
			{
				return this._Edad;
			}
			set
			{
				if ((this._Edad != value))
				{
					this._Edad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="NVarChar(50)")]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this._Mail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Posicion", DbType="Int")]
		public System.Nullable<int> Posicion
		{
			get
			{
				return this._Posicion;
			}
			set
			{
				if ((this._Posicion != value))
				{
					this._Posicion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Handicap", DbType="Int")]
		public System.Nullable<int> Handicap
		{
			get
			{
				return this._Handicap;
			}
			set
			{
				if ((this._Handicap != value))
				{
					this._Handicap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantPartidosJugados", DbType="Int NOT NULL")]
		public int CantPartidosJugados
		{
			get
			{
				return this._CantPartidosJugados;
			}
			set
			{
				if ((this._CantPartidosJugados != value))
				{
					this._CantPartidosJugados = value;
				}
			}
		}
	}
	
	public partial class Usuario_LResult
	{
		
		private int _Id_Usuario;
		
		private string _Nombre_Usuario;
		
		private string _Password_Usuario;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private System.Nullable<int> _Edad;
		
		private string _Mail;
		
		private System.Nullable<int> _Posicion;
		
		private System.Nullable<int> _Handicap;
		
		private int _CantPartidosJugados;
		
		public Usuario_LResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Usuario", DbType="Int NOT NULL")]
		public int Id_Usuario
		{
			get
			{
				return this._Id_Usuario;
			}
			set
			{
				if ((this._Id_Usuario != value))
				{
					this._Id_Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Usuario", DbType="NVarChar(50)")]
		public string Nombre_Usuario
		{
			get
			{
				return this._Nombre_Usuario;
			}
			set
			{
				if ((this._Nombre_Usuario != value))
				{
					this._Nombre_Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password_Usuario", DbType="NVarChar(50)")]
		public string Password_Usuario
		{
			get
			{
				return this._Password_Usuario;
			}
			set
			{
				if ((this._Password_Usuario != value))
				{
					this._Password_Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edad", DbType="Int")]
		public System.Nullable<int> Edad
		{
			get
			{
				return this._Edad;
			}
			set
			{
				if ((this._Edad != value))
				{
					this._Edad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="NVarChar(50)")]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this._Mail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Posicion", DbType="Int")]
		public System.Nullable<int> Posicion
		{
			get
			{
				return this._Posicion;
			}
			set
			{
				if ((this._Posicion != value))
				{
					this._Posicion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Handicap", DbType="Int")]
		public System.Nullable<int> Handicap
		{
			get
			{
				return this._Handicap;
			}
			set
			{
				if ((this._Handicap != value))
				{
					this._Handicap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantPartidosJugados", DbType="Int NOT NULL")]
		public int CantPartidosJugados
		{
			get
			{
				return this._CantPartidosJugados;
			}
			set
			{
				if ((this._CantPartidosJugados != value))
				{
					this._CantPartidosJugados = value;
				}
			}
		}
	}
	
	public partial class Partido_Interesado_LResult
	{
		
		private string _Nombre;
		
		private string _Apellido;
		
		private System.Nullable<int> _Edad;
		
		private System.Nullable<int> _Posicion;
		
		private System.Nullable<int> _Handicap;
		
		private string _Tipo_Jugador;
		
		public Partido_Interesado_LResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edad", DbType="Int")]
		public System.Nullable<int> Edad
		{
			get
			{
				return this._Edad;
			}
			set
			{
				if ((this._Edad != value))
				{
					this._Edad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Posicion", DbType="Int")]
		public System.Nullable<int> Posicion
		{
			get
			{
				return this._Posicion;
			}
			set
			{
				if ((this._Posicion != value))
				{
					this._Posicion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Handicap", DbType="Int")]
		public System.Nullable<int> Handicap
		{
			get
			{
				return this._Handicap;
			}
			set
			{
				if ((this._Handicap != value))
				{
					this._Handicap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo_Jugador", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tipo_Jugador
		{
			get
			{
				return this._Tipo_Jugador;
			}
			set
			{
				if ((this._Tipo_Jugador != value))
				{
					this._Tipo_Jugador = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
