//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_Anual_DDS_Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbInteresado
    {
        public System.Guid IdInteresado { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public int Edad { get; set; }
        public int Handicap { get; set; }
        public string Email { get; set; }
        public bool Aceptado { get; set; }
        public int CantidadPartidosJugados { get; set; }
        public System.Guid IdAmigoProponedor { get; set; }
        public System.Guid IdModalidad { get; set; }
        public int Posicion { get; set; }
        public string Condiciones { get; set; }
    }
}
