//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_Anual_DDS_Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbPartidoCalificaciones
    {
        public System.Guid IdPartidoCalificaciones { get; set; }
        public System.Guid IdPartido { get; set; }
        public System.Guid IdJugadorCriticado { get; set; }
        public int Calificacion { get; set; }
        public string Descripcion { get; set; }
        public System.Guid IdJugadorCritico { get; set; }
    }
}
