//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_Anual_DDS_Desktop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model2Container : DbContext
    {
        public Model2Container()
            : base("name=Model2Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DbPartido> DbPartidoSet { get; set; }
        public DbSet<DbInteresado> DbInteresadoSet { get; set; }
        public DbSet<DbPartidoCalificaciones> DbPartidoCalificacionesSet { get; set; }
        public DbSet<DbModalidad> DbModalidadSet { get; set; }
        public DbSet<DbDenegaciones> DbDenegacionesSet { get; set; }
    }
}
